In [68]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import datetime
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [69]:
train = pd.read_csv('train_users_2.csv')
session = pd.read_csv('sessions.csv')

In [70]:
train['gender'] = train['gender'].astype(str)
train = train.replace('-unknown-', np.nan)
train['gender'] = train['gender'].replace('nan', np.nan)

In [71]:
session['action'] = session['action'].replace('-unknown-', np.nan)
session['action_type'] = session['action_type'].replace('-unknown-', np.nan)
session['action_detail'] = session['action_detail'].replace('-unknown-', np.nan)
session['device_type'] = session['device_type'].replace('-unknown-', np.nan)
session = session.rename(columns={'user_id': 'id'})

In [72]:
sec = session.groupby(['id']).sum()

In [73]:
df2 = pd.merge(train,session)

In [74]:
secs = df2.groupby(['id']).sum()
secs.head()

timestamp_first_active      age  signup_flow  secs_elapsed
id                                                                    
00023iyk9l         805620567818080   1240.0            0      867896.0
001wyh0pz8        1812638175409440      0.0         2070      282965.0
0028jgx1x1         624359254423609      0.0            0      297010.0
002qnbzfs5       15890796280441576  20514.0        19725     6487080.0
0035hobuyj        9848509986780006      0.0            0     5724670.0

In [75]:
df = pd.merge(train,secs)
df = df.dropna(subset=['country_destination'])
df.shape

(494, 17)

In [76]:
df.loc[df.age > 95, 'age'] = np.nan
df.loc[df.age < 18, 'age'] = np.nan

In [77]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [78]:
df = df.dropna()
df.gender = df.gender.astype("category").cat.codes
df.signup_method = df.signup_method.astype("category").cat.codes
df.language = df.language.astype("category").cat.codes
df.affiliate_channel=df.affiliate_channel.astype("category").cat.codes
df.affiliate_provider=df.affiliate_provider.astype("category").cat.codes
df.first_affiliate_tracked = df.first_affiliate_tracked.astype("category").cat.codes
df.signup_app = df.signup_app.astype("category").cat.codes
df.first_device_type = df.first_device_type.astype("category").cat.codes
df.first_browser=df.first_browser.astype("category").cat.codes
df.country_destination=df.country_destination.astype("category").cat.codes

In [79]:
df = df.drop(['id','date_account_created','date_first_booking'], axis=1)


In [80]:
X = df.drop(['country_destination'], axis=1).values

In [81]:

X.reshape(-1,1)

array([[2.01401021e+13],
       [1.00000000e+00],
       [3.90000000e+01],
       ...,
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00]])

In [82]:
y= df['country_destination'].values
y.reshape(-1,1)

array([[8],
       [7],
       [7],
       [7],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [4],
       [7],
       [7],
       [7],
       [5],
       [8],
       [7],
       [7],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [1],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [4],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [8],
       [7],
       [7],
       [3],
       [8],
       [1],
       [7],
       [7],
       [3],
       [7],
       [7],
       [7],
       [7],
       [1],
       [7],
       [8],
       [8],
       [7],
       [7],
       [7],
       [7],
       [7],
       [4],
       [7],
       [8],
       [7],
       [0],
       [7],
       [0],
       [7],
       [7],
       [7],
       [7],
    

In [83]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics, datasets
from sklearn.model_selection import train_test_split

In [84]:
X = df[['gender','signup_method','language','affiliate_channel','affiliate_provider','first_affiliate_tracked','signup_app',
'first_device_type','first_browser','age']]
y = df['country_destination']

clf = LogisticRegression()

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=42)

In [86]:
clf.fit(X_train, y_train)

/Users/irene/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/irene/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [87]:
print(accuracy_score(clf.predict(X_test), y_test))

0.696969696969697


In [23]:
from sklearn.linear_model import Lasso
names = df.drop('country_destination', axis=1).columns

In [88]:
lasso = Lasso(alpha=0)
lasso_coef=lasso.fit(X, y).coef_
_ = plt.plot(range(len(names)), lasso_coef)
_ = plt.xticks(range(len(names)), names, rotation = 90)
_ = plt.ylabel('Coefficients')
_ = plt.axhline(0, color='white')

NameError: name 'Lasso' is not defined

In [ ]:
dropping time first active, signupflow, language, and secs_elapsed


In [47]:
df

timestamp_first_active  gender        age  signup_method  signup_flow  \
1            20140102053844       1  39.000000              0           25   
2            20140102171712       0  27.000000              0           25   
9            20140108180025       1  39.000000              0            0   
10           20140110211722       0  35.000000              0           24   
18           20140112225145       1  32.000000              0           25   
20           20140113131435       1  41.000000              0           25   
22           20140113233821       1  32.000000              0           25   
23           20140114050527       0  24.000000              0           25   
32           20140118153626       0  26.000000              0           25   
33           20140118205203       1  36.000000              0           25   
34           20140119011908       1  23.000000              0           25   
36           20140120014816       0  26.000000              0           25   
40           20140121195928       0  40.000000              0           25   
42           20140122150217       1  34.102296              0           24   
43           20140122155323       1  45.000000              0           25   
44           20140123054520       0  23.000000              0           25   
45           20140123191806       0  33.000000              0           24   
47           20140123222228       1  29.000000              0           25   
51           20140125023321       1  31.000000              0           25   
56           20140126064638       0  34.000000              0           25   
58           20140126141305       1  36.000000              0           25   
62           20140128034751       1  38.000000              0           25   
64           20140128184946       1  32.000000              0           25   
68           20140129202615       1  26.000000              0           25   
72           20140131024839       1  29.000000              0           25   
74           20140131044652       0  28.000000              0           24   
75           20140131195437       1  28.000000              0           25   
81           20140205021753       0  32.000000              0           24   
91           20140208014425       1  29.000000              0           25   
92           20140208041811       1  37.000000              0           25   
..                      ...     ...        ...            ...          ...   
416          20140529200241       0  46.000000              0            0   
419          20140529204255       0  32.000000              0            0   
420          20140529210350       0  32.000000              0            0   
421          20140529215043       0  25.000000              1            0   
430          20140530144657       0  26.000000              0            0   
435          20140601115509       1  22.000000              0           24   
436          20140602063039       1  30.000000              0           24   
437          20140603050523       0  29.000000              0           24   
439          20140604011712       1  26.000000              1            0   
443          20140605054955       1  36.000000              0           24   
447          20140606232646       1  27.000000              0           24   
452          20140608230237       0  30.000000              1            0   
453          20140608231444       0  29.000000              0           24   
455          20140609202439       1  41.000000              0           24   
456          20140609222830       1  30.000000              0           24   
458          20140611223750       0  34.102296              0           25   
460          20140612221656       1  33.000000              0           24   
461          20140613164132       0  28.000000              0           24   
465          20140616081116       0  28.000000              0           24   
466          20140616195941

In [64]:
df = df.drop(['timestamp_first_active','signup_flow','language','secs_elapsed'], axis=1)

In [92]:
X1 = df.drop(['country_destination'],axis=1).values
X1.reshape(-1,1)

array([[2.01401021e+13],
       [1.00000000e+00],
       [3.90000000e+01],
       ...,
       [0.00000000e+00],
       [0.00000000e+00],
       [0.00000000e+00]])

In [93]:
y1 = df.country_destination.values
y1.reshape(-1,1)

array([[8],
       [7],
       [7],
       [7],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [4],
       [7],
       [7],
       [7],
       [5],
       [8],
       [7],
       [7],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [1],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [4],
       [7],
       [8],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [7],
       [8],
       [7],
       [7],
       [3],
       [8],
       [1],
       [7],
       [7],
       [3],
       [7],
       [7],
       [7],
       [7],
       [1],
       [7],
       [8],
       [8],
       [7],
       [7],
       [7],
       [7],
       [7],
       [4],
       [7],
       [8],
       [7],
       [0],
       [7],
       [0],
       [7],
       [7],
       [7],
       [7],
    

In [94]:
logreg = LogisticRegression()
X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size = 0.4, random_state=42)

In [96]:
logreg.fit(X_train1, y_train1)
y_pred1 =logreg.predict(X_test1)
print(confusion_matrix(y_test1, y_pred1))
print(classification_report(y_test1, y_pred1))
print(accuracy_score(logreg.predict(X_test1), y_test1))

[[ 0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  5  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0 47  0]
 [ 0  0  0  0  0  0  7  0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         5
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         2
           7       0.71      1.00      0.83        47
           8       0.00      0.00      0.00         7

   micro avg       0.71      0.71      0.71        66
   macro avg       0.09      0.12      0.10        66
weighted avg       0.51      0.71      0.59        66

0.7121212121212122


/Users/irene/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/irene/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/irene/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/irene/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/Users/irene/anaconda

In [82]:
#SVM
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC()
svc.fit(X_train1, y_train1)

print("train set accuracy SVM: {:.2f}".format(svc.score(X_train1, y_train1)))
print("test set accuracy SVM : {:.2f}".format(svc.score(X_test1, y_test1)))

train set accuracy SVM: 0.78
test set accuracy SVM : 0.71


/Users/irene/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [79]:
svm = SVC(kernel='rbf', C=10.0, random_state=0, gamma=0.10)


In [83]:
svm.fit(X_train1, y_train1)
y_pred2 = svm.predict(X_test1)
print('Accuracy: %.2f' % accuracy_score(y_test1, y_pred2))

Accuracy: 0.58


In [95]:
target = df.country_destination

timestamp_first_active  gender        age  signup_method  signup_flow  \
1            20140102053844       1  39.000000              0           25   
2            20140102171712       0  27.000000              0           25   
9            20140108180025       1  39.000000              0            0   
10           20140110211722       0  35.000000              0           24   
18           20140112225145       1  32.000000              0           25   
20           20140113131435       1  41.000000              0           25   
22           20140113233821       1  32.000000              0           25   
23           20140114050527       0  24.000000              0           25   
32           20140118153626       0  26.000000              0           25   
33           20140118205203       1  36.000000              0           25   
34           20140119011908       1  23.000000              0           25   
36           20140120014816       0  26.000000              0           25   
40           20140121195928       0  40.000000              0           25   
42           20140122150217       1  34.102296              0           24   
43           20140122155323       1  45.000000              0           25   
44           20140123054520       0  23.000000              0           25   
45           20140123191806       0  33.000000              0           24   
47           20140123222228       1  29.000000              0           25   
51           20140125023321       1  31.000000              0           25   
56           20140126064638       0  34.000000              0           25   
58           20140126141305       1  36.000000              0           25   
62           20140128034751       1  38.000000              0           25   
64           20140128184946       1  32.000000              0           25   
68           20140129202615       1  26.000000              0           25   
72           20140131024839       1  29.000000              0           25   
74           20140131044652       0  28.000000              0           24   
75           20140131195437       1  28.000000              0           25   
81           20140205021753       0  32.000000              0           24   
91           20140208014425       1  29.000000              0           25   
92           20140208041811       1  37.000000              0           25   
..                      ...     ...        ...            ...          ...   
416          20140529200241       0  46.000000              0            0   
419          20140529204255       0  32.000000              0            0   
420          20140529210350       0  32.000000              0            0   
421          20140529215043       0  25.000000              1            0   
430          20140530144657       0  26.000000              0            0   
435          20140601115509       1  22.000000              0           24   
436          20140602063039       1  30.000000              0           24   
437          20140603050523       0  29.000000              0           24   
439          20140604011712       1  26.000000              1            0   
443          20140605054955       1  36.000000              0           24   
447          20140606232646       1  27.000000              0           24   
452          20140608230237       0  30.000000              1            0   
453          20140608231444       0  29.000000              0           24   
455          20140609202439       1  41.000000              0           24   
456          20140609222830       1  30.000000              0           24   
458          20140611223750       0  34.102296              0           25   
460          20140612221656       1  33.000000              0           24   
461          20140613164132       0  28.000000              0           24   
465          20140616081116       0  28.000000              0           24   
466          20140616195941

In [96]:
X = df.drop(['country_destination'],axis=1)

In [97]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y, test_size=0.2, random_state=123)

In [1]:
import pip

In [2]:
!pip3 install xgboost

In [3]:
import xgboost as xgb

In [35]:
train = pd.read_csv('train_users_2.csv')
session = pd.read_csv('sessions.csv')

In [36]:
session = session.rename(columns={'user_id': 'id'})

In [37]:
df2 = pd.merge(train,session)

In [38]:
secs = df2.groupby(['id']).sum()


In [39]:
df = pd.merge(train,secs)


In [40]:
df = df.drop(['id','date_account_created','date_first_booking'], axis=1)
df.head()

timestamp_first_active     gender   age signup_method  signup_flow  \
0          20140101044849       MALE  29.0         basic           25   
1          20140102053844       MALE  39.0         basic           25   
2          20140102171712     FEMALE  27.0         basic           25   
3          20140104063133  -unknown-  43.0         basic           25   
4          20140105051317       MALE  78.0         basic           25   

  language affiliate_channel affiliate_provider first_affiliate_tracked  \
0       zh            direct             direct               untracked   
1       en            direct             direct               untracked   
2       en            direct             direct               untracked   
3       en            direct             direct               untracked   
4       en            direct             direct               untracked   

  signup_app first_device_type  first_browser country_destination  \
0        iOS            iPhone      -unknown-                  US   
1        iOS            iPhone  Mobile Safari               other   
2        iOS            iPhone  Mobile Safari                  US   
3        iOS              iPad  Mobile Safari               other   
4        iOS   Windows Desktop        Firefox                 NDF   

   secs_elapsed  
0           0.0  
1           0.0  
2           0.0  
3           0.0  
4           0.0

In [41]:
y = df.country_destination
X = df.drop('country_destination',axis=1)

In [43]:
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [59]:
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(y)
label_encoded_y = label_encoder.transform(y)

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, label_encoded_y, test_size = 0.4, random_state=42)

In [61]:
model = xgb.XGBClassifier()
model.fit(X_train, y_train)
print(model)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)


In [50]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 494 entries, 0 to 493
Data columns (total 13 columns):
timestamp_first_active     494 non-null int64
gender                     494 non-null object
age                        494 non-null float64
signup_method              494 non-null object
signup_flow                494 non-null int64
language                   494 non-null object
affiliate_channel          494 non-null object
affiliate_provider         494 non-null object
first_affiliate_tracked    489 non-null object
signup_app                 494 non-null object
first_device_type          494 non-null object
first_browser              494 non-null object
secs_elapsed               494 non-null float64
dtypes: float64(2), int64(2), object(9)
memory usage: 54.0+ KB


In [56]:
X['gender'] = X['gender'].astype(str)
X.gender = X.gender.astype("category").cat.codes
X.signup_method = X.signup_method.astype("category").cat.codes
X.language = X.language.astype("category").cat.codes
X.affiliate_channel=X.affiliate_channel.astype("category").cat.codes
X.affiliate_provider=X.affiliate_provider.astype("category").cat.codes
X.first_affiliate_tracked = X.first_affiliate_tracked.astype("category").cat.codes
X.signup_app = X.signup_app.astype("category").cat.codes
X.first_device_type = X.first_device_type.astype("category").cat.codes
X.first_browser=X.first_browser.astype("category").cat.codes


In [58]:
y=y.astype("category").cat.codes

In [62]:
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

In [63]:
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 56.57%


In [67]:

# set missing values to 0
X[X == '-unknown-'] = 0
# convert to numeric
X = X.astype('float32')
# encode Y class values as integers
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(y)
label_encoded_y = label_encoder.transform(y)
# split data into train and test sets

X_train, X_test, y_train, y_test = train_test_split(X, label_encoded_y, test_size=0.33, random_state=7)
# fit model no training data
model = xgb.XGBClassifier()
model.fit(X_train, y_train)
print(model)
# make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]
# evaluate predictions
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)
Accuracy: 58.54%
